# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (5)
# #########################################################################

class CampoFaltante(BaseModel):
    campo: typing.Optional[str] = Field(default=None, description='nome do campo ausente')
    criticidade: typing.Optional[typing.Union[typing_extensions.Literal['bloqueante'], typing_extensions.Literal['importante'], typing_extensions.Literal['opcional']]] = None
    justificativa: typing.Optional[str] = Field(default=None, description='por que esse campo é necessário')

class ExtracaoSinistro(BaseModel):
    tipo_sinistro: typing.Optional[types.TipoSinistro] = None
    urgencia: typing.Optional[types.Urgencia] = None
    plataforma_mencionada: typing.Optional[types.Plataforma] = Field(default=None, description='plataforma de mobilidade/delivery citada na narrativa. Use NAO_MENCIONADA se não houver referência explícita.')
    data_ocorrencia: typing.Optional[str] = Field(default=None, description='ISO 8601 YYYY-MM-DD se mencionada; null caso contrário. Nunca inventar.')
    hora_aproximada: typing.Optional[str] = Field(default=None, description='HH:MM se mencionada')
    local_ocorrencia: typing.Optional[str] = Field(default=None, description='cidade, rua, ou descrição textual')
    descricao_evento: typing.Optional[str] = Field(default=None, description='resumo objetivo em até 300 caracteres, em terceira pessoa')
    veiculo: typing.Optional["Veiculo"] = None
    pessoas: typing.List["PessoaEnvolvida"]
    ha_vitimas_fatais: typing.Optional[bool] = None
    ha_feridos: typing.Optional[bool] = None
    envolve_terceiros: typing.Optional[bool] = None
    documentos_mencionados: typing.List[str] = Field(description='BO, atestado, CNH, CRLV, nota fiscal, fotos, etc')
    confianca: typing.Optional[float] = Field(default=None, description='0.0 a 1.0 - sua certeza REAL na extração. Use < 0.5 se narrativa ambígua.')
    campos_faltantes: typing.List["CampoFaltante"] = Field(description='lista estruturada de gaps para abrir o sinistro')
    red_flags: typing.List["RedFlag"] = Field(description='sinais de inconsistência, fraude potencial, ou narrativa atípica')
    requer_esclarecimento: typing.Optional[bool] = Field(default=None, description='true APENAS se o EVENTO em si não ficou claro. NÃO use true só porque faltam documentos.')
    perguntas_sugeridas: typing.List[str] = Field(description='perguntas objetivas para o bot fazer ao segurado, se requer_esclarecimento=true')

class PessoaEnvolvida(BaseModel):
    papel: typing.Optional[typing.Union[typing_extensions.Literal['segurado'], typing_extensions.Literal['terceiro'], typing_extensions.Literal['testemunha'], typing_extensions.Literal['vitima'], typing_extensions.Literal['desconhecido']]] = None
    descricao: typing.Optional[str] = Field(default=None, description='texto curto identificando a pessoa')
    ferido: typing.Optional[bool] = None

class RedFlag(BaseModel):
    tipo: typing.Optional[typing.Union[typing_extensions.Literal['timing'], typing_extensions.Literal['contradicao'], typing_extensions.Literal['detalhe_suspeito'], typing_extensions.Literal['historico'], typing_extensions.Literal['outro']]] = None
    descricao: typing.Optional[str] = None
    severidade: typing.Optional[typing.Union[typing_extensions.Literal['baixa'], typing_extensions.Literal['media'], typing_extensions.Literal['alta']]] = None

class Veiculo(BaseModel):
    placa: typing.Optional[str] = Field(default=None, description='formato AAA0A00 se mencionada')
    tipo: typing.Optional[types.TipoVeiculo] = None
    descricao_livre: typing.Optional[str] = Field(default=None, description='marca/modelo/cor se citado')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
