# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
from baml_py import type_builder
from baml_py import baml_py
# These are exports, not used here, hence the linter is disabled
from baml_py.baml_py import FieldType, EnumValueBuilder, EnumBuilder, ClassBuilder # noqa: F401 # pylint: disable=unused-import
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME

class TypeBuilder(type_builder.TypeBuilder):
    def __init__(self):
        super().__init__(classes=set(
          ["CampoFaltante","ExtracaoSinistro","PessoaEnvolvida","RedFlag","Veiculo",]
        ), enums=set(
          ["TipoSinistro","TipoVeiculo","Urgencia",]
        ), runtime=DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME)

    # #########################################################################
    # Generated enums 3
    # #########################################################################

    @property
    def TipoSinistro(self) -> "TipoSinistroViewer":
        return TipoSinistroViewer(self)

    @property
    def TipoVeiculo(self) -> "TipoVeiculoViewer":
        return TipoVeiculoViewer(self)

    @property
    def Urgencia(self) -> "UrgenciaViewer":
        return UrgenciaViewer(self)


    # #########################################################################
    # Generated classes 5
    # #########################################################################

    @property
    def CampoFaltante(self) -> "CampoFaltanteViewer":
        return CampoFaltanteViewer(self)

    @property
    def ExtracaoSinistro(self) -> "ExtracaoSinistroViewer":
        return ExtracaoSinistroViewer(self)

    @property
    def PessoaEnvolvida(self) -> "PessoaEnvolvidaViewer":
        return PessoaEnvolvidaViewer(self)

    @property
    def RedFlag(self) -> "RedFlagViewer":
        return RedFlagViewer(self)

    @property
    def Veiculo(self) -> "VeiculoViewer":
        return VeiculoViewer(self)



# #########################################################################
# Generated enums 3
# #########################################################################

class TipoSinistroAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("TipoSinistro")
        self._values: typing.Set[str] = set([  "MA",  "IPA",  "DITA",  "DMHO",  "MAC",  "IAT",  "AF",  "BAGAGEM",  "INDEFINIDO",  ])
        self._vals = TipoSinistroValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "TipoSinistroValues":
        return self._vals


class TipoSinistroViewer(TipoSinistroAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class TipoSinistroValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def MA(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MA"))
    
    @property
    def IPA(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("IPA"))
    
    @property
    def DITA(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("DITA"))
    
    @property
    def DMHO(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("DMHO"))
    
    @property
    def MAC(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MAC"))
    
    @property
    def IAT(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("IAT"))
    
    @property
    def AF(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("AF"))
    
    @property
    def BAGAGEM(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("BAGAGEM"))
    
    @property
    def INDEFINIDO(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("INDEFINIDO"))
    
    


class TipoVeiculoAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("TipoVeiculo")
        self._values: typing.Set[str] = set([  "MOTO",  "CARRO",  "BIKE",  "CAMINHAO",  "NAO_MENCIONADO",  ])
        self._vals = TipoVeiculoValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "TipoVeiculoValues":
        return self._vals


class TipoVeiculoViewer(TipoVeiculoAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class TipoVeiculoValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def MOTO(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MOTO"))
    
    @property
    def CARRO(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("CARRO"))
    
    @property
    def BIKE(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("BIKE"))
    
    @property
    def CAMINHAO(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("CAMINHAO"))
    
    @property
    def NAO_MENCIONADO(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("NAO_MENCIONADO"))
    
    


class UrgenciaAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("Urgencia")
        self._values: typing.Set[str] = set([  "BAIXA",  "MEDIA",  "ALTA",  "CRITICA",  ])
        self._vals = UrgenciaValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "UrgenciaValues":
        return self._vals


class UrgenciaViewer(UrgenciaAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class UrgenciaValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def BAIXA(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("BAIXA"))
    
    @property
    def MEDIA(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MEDIA"))
    
    @property
    def ALTA(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("ALTA"))
    
    @property
    def CRITICA(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("CRITICA"))
    
    



# #########################################################################
# Generated classes 5
# #########################################################################

class CampoFaltanteAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("CampoFaltante")
        self._properties: typing.Set[str] = set([  "campo",  "criticidade",  "justificativa",  ])
        self._props = CampoFaltanteProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "CampoFaltanteProperties":
        return self._props


class CampoFaltanteViewer(CampoFaltanteAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class CampoFaltanteProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def campo(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("campo"))
    
    @property
    def criticidade(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("criticidade"))
    
    @property
    def justificativa(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("justificativa"))
    
    


class ExtracaoSinistroAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("ExtracaoSinistro")
        self._properties: typing.Set[str] = set([  "tipo_sinistro",  "urgencia",  "data_ocorrencia",  "hora_aproximada",  "local_ocorrencia",  "descricao_evento",  "veiculo",  "pessoas",  "ha_vitimas_fatais",  "ha_feridos",  "envolve_terceiros",  "documentos_mencionados",  "confianca",  "campos_faltantes",  "red_flags",  "requer_esclarecimento",  "perguntas_sugeridas",  ])
        self._props = ExtracaoSinistroProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ExtracaoSinistroProperties":
        return self._props


class ExtracaoSinistroViewer(ExtracaoSinistroAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class ExtracaoSinistroProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def tipo_sinistro(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("tipo_sinistro"))
    
    @property
    def urgencia(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("urgencia"))
    
    @property
    def data_ocorrencia(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("data_ocorrencia"))
    
    @property
    def hora_aproximada(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("hora_aproximada"))
    
    @property
    def local_ocorrencia(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("local_ocorrencia"))
    
    @property
    def descricao_evento(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("descricao_evento"))
    
    @property
    def veiculo(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("veiculo"))
    
    @property
    def pessoas(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("pessoas"))
    
    @property
    def ha_vitimas_fatais(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("ha_vitimas_fatais"))
    
    @property
    def ha_feridos(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("ha_feridos"))
    
    @property
    def envolve_terceiros(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("envolve_terceiros"))
    
    @property
    def documentos_mencionados(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("documentos_mencionados"))
    
    @property
    def confianca(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("confianca"))
    
    @property
    def campos_faltantes(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("campos_faltantes"))
    
    @property
    def red_flags(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("red_flags"))
    
    @property
    def requer_esclarecimento(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("requer_esclarecimento"))
    
    @property
    def perguntas_sugeridas(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("perguntas_sugeridas"))
    
    


class PessoaEnvolvidaAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("PessoaEnvolvida")
        self._properties: typing.Set[str] = set([  "papel",  "descricao",  "ferido",  ])
        self._props = PessoaEnvolvidaProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "PessoaEnvolvidaProperties":
        return self._props


class PessoaEnvolvidaViewer(PessoaEnvolvidaAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class PessoaEnvolvidaProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def papel(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("papel"))
    
    @property
    def descricao(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("descricao"))
    
    @property
    def ferido(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("ferido"))
    
    


class RedFlagAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("RedFlag")
        self._properties: typing.Set[str] = set([  "tipo",  "descricao",  "severidade",  ])
        self._props = RedFlagProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "RedFlagProperties":
        return self._props


class RedFlagViewer(RedFlagAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class RedFlagProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def tipo(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("tipo"))
    
    @property
    def descricao(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("descricao"))
    
    @property
    def severidade(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("severidade"))
    
    


class VeiculoAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Veiculo")
        self._properties: typing.Set[str] = set([  "placa",  "tipo",  "descricao_livre",  ])
        self._props = VeiculoProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "VeiculoProperties":
        return self._props


class VeiculoViewer(VeiculoAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class VeiculoProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def placa(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("placa"))
    
    @property
    def tipo(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("tipo"))
    
    @property
    def descricao_livre(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("descricao_livre"))
    
    

