# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (4)
# #########################################################################

class Plataforma(str, Enum):
    UBER = "UBER"
    NOVENTA_E_NOVE = "NOVENTA_E_NOVE"
    IFOOD = "IFOOD"
    RAPPI = "RAPPI"
    LOGGI = "LOGGI"
    LALAMOVE = "LALAMOVE"
    OUTRA_PLATAFORMA = "OUTRA_PLATAFORMA"
    NAO_MENCIONADA = "NAO_MENCIONADA"

class TipoSinistro(str, Enum):
    MA = "MA"
    IPA = "IPA"
    DITA = "DITA"
    DMHO = "DMHO"
    MAC = "MAC"
    IAT = "IAT"
    AF = "AF"
    BAGAGEM = "BAGAGEM"
    INDEFINIDO = "INDEFINIDO"

class TipoVeiculo(str, Enum):
    MOTO = "MOTO"
    CARRO = "CARRO"
    BIKE = "BIKE"
    CAMINHAO = "CAMINHAO"
    NAO_MENCIONADO = "NAO_MENCIONADO"

class Urgencia(str, Enum):
    BAIXA = "BAIXA"
    MEDIA = "MEDIA"
    ALTA = "ALTA"
    CRITICA = "CRITICA"

# #########################################################################
# Generated classes (5)
# #########################################################################

class CampoFaltante(BaseModel):
    campo: str = Field(description='nome do campo ausente')
    criticidade: typing.Union[typing_extensions.Literal['bloqueante'], typing_extensions.Literal['importante'], typing_extensions.Literal['opcional']]
    justificativa: str = Field(description='por que esse campo é necessário')

class ExtracaoSinistro(BaseModel):
    tipo_sinistro: TipoSinistro
    urgencia: Urgencia
    plataforma_mencionada: Plataforma = Field(description='plataforma de mobilidade/delivery citada na narrativa. Use NAO_MENCIONADA se não houver referência explícita.')
    data_ocorrencia: typing.Optional[str] = Field(default=None, description='ISO 8601 YYYY-MM-DD se mencionada; null caso contrário. Nunca inventar.')
    hora_aproximada: typing.Optional[str] = Field(default=None, description='HH:MM se mencionada')
    local_ocorrencia: typing.Optional[str] = Field(default=None, description='cidade, rua, ou descrição textual')
    descricao_evento: str = Field(description='resumo objetivo em até 300 caracteres, em terceira pessoa')
    veiculo: typing.Optional["Veiculo"] = None
    pessoas: typing.List["PessoaEnvolvida"]
    ha_vitimas_fatais: bool
    ha_feridos: bool
    envolve_terceiros: bool
    documentos_mencionados: typing.List[str] = Field(description='BO, atestado, CNH, CRLV, nota fiscal, fotos, etc')
    confianca: float = Field(description='0.0 a 1.0 - sua certeza REAL na extração. Use < 0.5 se narrativa ambígua.')
    campos_faltantes: typing.List["CampoFaltante"] = Field(description='lista estruturada de gaps para abrir o sinistro')
    red_flags: typing.List["RedFlag"] = Field(description='sinais de inconsistência, fraude potencial, ou narrativa atípica')
    requer_esclarecimento: bool = Field(description='true APENAS se o EVENTO em si não ficou claro. NÃO use true só porque faltam documentos.')
    perguntas_sugeridas: typing.List[str] = Field(description='perguntas objetivas para o bot fazer ao segurado, se requer_esclarecimento=true')

class PessoaEnvolvida(BaseModel):
    papel: typing.Union[typing_extensions.Literal['segurado'], typing_extensions.Literal['terceiro'], typing_extensions.Literal['testemunha'], typing_extensions.Literal['vitima'], typing_extensions.Literal['desconhecido']]
    descricao: typing.Optional[str] = Field(default=None, description='texto curto identificando a pessoa')
    ferido: bool

class RedFlag(BaseModel):
    tipo: typing.Union[typing_extensions.Literal['timing'], typing_extensions.Literal['contradicao'], typing_extensions.Literal['detalhe_suspeito'], typing_extensions.Literal['historico'], typing_extensions.Literal['outro']]
    descricao: str
    severidade: typing.Union[typing_extensions.Literal['baixa'], typing_extensions.Literal['media'], typing_extensions.Literal['alta']]

class Veiculo(BaseModel):
    placa: typing.Optional[str] = Field(default=None, description='formato AAA0A00 se mencionada')
    tipo: TipoVeiculo
    descricao_livre: typing.Optional[str] = Field(default=None, description='marca/modelo/cor se citado')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
