# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CampoFaltante": types.CampoFaltante,
    "stream_types.CampoFaltante": stream_types.CampoFaltante,

    "types.ExtracaoSinistro": types.ExtracaoSinistro,
    "stream_types.ExtracaoSinistro": stream_types.ExtracaoSinistro,

    "types.PessoaEnvolvida": types.PessoaEnvolvida,
    "stream_types.PessoaEnvolvida": stream_types.PessoaEnvolvida,

    "types.RedFlag": types.RedFlag,
    "stream_types.RedFlag": stream_types.RedFlag,

    "types.Veiculo": types.Veiculo,
    "stream_types.Veiculo": stream_types.Veiculo,


    "types.Plataforma": types.Plataforma,

    "types.TipoSinistro": types.TipoSinistro,

    "types.TipoVeiculo": types.TipoVeiculo,

    "types.Urgencia": types.Urgencia,

}